"""Golden-output tests: fixed DSL input -> byte-exact expected artifacts.

These lock the emitted files so a codegen change that alters output (even a
spacing/JSON change) is immediately visible.  Golden strings below were
captured from the generators after the 26.2 verification work.
"""
from __future__ import annotations

from pathlib import Path

from helpers import EXAMPLES, read, render

# ---------------------------------------------------------------------------
# sources-under-test
# ---------------------------------------------------------------------------

CHAOS = EXAMPLES / "chaos.py"
KJD = EXAMPLES / "kubejs_demo.py"
FAB = EXAMPLES / "fabric_demo.py"

PACK_MCMETA = """\
{
  "pack": {
    "pack_format": 107,
    "description": "Example mod for the pymod DSL."
  }
}
"""

TAG_MAGIC = """\
{
  "replace": false,
  "values": [
    "minecraft:stone",
    "minecraft:dirt"
  ]
}
"""

ADV_ON_STICK = """\
{
  "criteria": {
    "triggered": {
      "trigger": "minecraft:item_used_on_block",
      "conditions": {
        "item": {
          "items": [
            "minecraft:stick"
          ]
        }
      }
    }
  },
  "rewards": {
    "function": "chaoscube:on_stick"
  }
}
"""

FUNC_ON_STICK = """\
# generated by pymod: player.use_item (on_stick)
tellraw @s {"text": "You used a stick!"}
give @s minecraft:diamond 1
playsound minecraft:block.note_block.pling player @s 0 0 0 0.5 1
"""

KUBEJS_KJD = """\
// generated by pymod
// mod: KubeJS Demo (kjdemo v1.0.0)

ServerEvents.tags((event) => {
  event.add('kjdemo:items/rare', ['minecraft:diamond', 'minecraft:emerald']);
});

// player.use_item (on_use)
ItemEvents.rightClicked((event) => {
  if (event.item.id === "minecraft:stick") {
    event.player.tell("sticky!");
    event.player.give(Item.of("minecraft:diamond", 2));
  }
});

// block.broken (on_break)
BlockEvents.broken((event) => {
  event.server.runCommandSilent("setblock 0 -1 0 minecraft:bedrock");
});
"""

FAB_MAIN = """\
package net.pymod.fdemo;

import net.fabricmc.api.ModInitializer;
import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.Identifier;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.state.BlockBehaviour;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class FdemoMod implements ModInitializer {
    public static final String MOD_ID = "fdemo";
    public static final Logger LOGGER = LoggerFactory.getLogger(MOD_ID);

    @Override
    public void onInitialize() {
        Registry.register(BuiltInRegistries.ITEM, Identifier.fromNamespaceAndPath(MOD_ID, "ruby"), new Item(new Item.Properties().stacksTo(64)));
        Registry.register(BuiltInRegistries.BLOCK, Identifier.fromNamespaceAndPath(MOD_ID, "ruby_ore"), new Block(BlockBehaviour.Properties.of().strength(3.0f)));
        LOGGER.info("{} initialized", MOD_ID);
    }
}
"""

FAB_BUILD_GRADLE = """\
plugins {
    id("fabric-loom") version "1.17.19"
}

version = "1.0.0"
group = "net.pymod.fdemo"

base {
    archivesName = "fdemo"
}

repositories {
    mavenCentral()
}

dependencies {
    minecraft("com.mojang:minecraft:26.2")
    // 26.x: Mojang ships a named (de-obfuscated) jar. Loom needs a mappings
    // layer with a 'named' column; the generated identity tiny (official ->
    // intermediary -> named, all identical) provides exactly that with zero
    // renames. Published yarn / mojang mappings don't exist for 26.2.
    mappings(loom.layered { mappings(file("mappings/identity.tiny")) })
    modImplementation("net.fabricmc:fabric-loader:0.19.3")
    modImplementation("net.fabricmc.fabric-api:fabric-api:0.156.0+26.2")
}

java {
    withSourcesJar()
}

// Sources are already in Mojang names (identity mappings / named jar), so the
// sources-jar remap has nothing to do -- and the empty identity tree would fail it.
tasks.named("remapSourcesJar") {
    enabled = false
}

tasks.withType<JavaCompile>().configureEach {
    options.release.set(25)
}
"""

IDENTITY_TINY = "tiny\t2\t0\tofficial\tintermediary\tnamed\n"


def test_datapack_golden(tmp_path):
    render("datapack", CHAOS.read_text(encoding="utf-8"), tmp_path)
    assert read(tmp_path / "pack.mcmeta") == PACK_MCMETA
    assert read(tmp_path / "data/chaoscube/tags/blocks/magic.json") == TAG_MAGIC
    assert read(tmp_path / "data/chaoscube/advancement/on_stick.json") == ADV_ON_STICK
    assert read(tmp_path / "data/chaoscube/function/on_stick.mcfunction") == FUNC_ON_STICK


def test_kubejs_golden(tmp_path):
    render("kubejs", KJD.read_text(encoding="utf-8"), tmp_path)
    assert read(tmp_path / "server_scripts/kjdemo.js") == KUBEJS_KJD


def test_fabric_golden(tmp_path):
    render("fabric", FAB.read_text(encoding="utf-8"), tmp_path)
    java = next(tmp_path.rglob("*.java"))
    assert java.read_text(encoding="utf-8") == FAB_MAIN
    assert read(tmp_path / "build.gradle.kts") == FAB_BUILD_GRADLE
    assert read(tmp_path / "mappings/identity.tiny") == IDENTITY_TINY